### ISSUE TITLE
Where is the ReadMe?

### ISSUE THREAD

**Issue by Hiram9270** [MatteoF94/ARTSLAM#1]
I want to reproduce your code ,but I can't find the readme.Thanks.

**Comment by MatteoF94** [comment]
The code in this repo corresponds to an old version of ART-SLAM, and we will release the current version after/upon acceptance of the corresponding paper.

Nevertheless, you can test this previous version to see the working principle of the system. You can directly download a demo at [https://docs.google.com/uc?export=download&id=1tj5TTF31TkUsX498bxIyXrMmb_0cPjCG], which also contains the instructions needed.
